name: CRIAR IMAGEM DOCKER

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REPO_URL: ${{ secrets.REPO_URL }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clonando o projeto na máquina de CI
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Buildando e subindo a imagem pro Docker Hub
      run: |
        docker build -t ${{ env.REPO_URL }}/teste-cicd .
        docker push ${{ env.REPO_URL }}/teste-cicd
